# Generated by Django 3.1 on 2020-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PigBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pigid', models.CharField(max_length=16, unique=True, verbose_name='身份码')),
                ('earid', models.CharField(max_length=16, verbose_name='耳标号')),
                ('pigkind', models.CharField(max_length=20, null=True, verbose_name='品种')),
                ('malepignum', models.CharField(max_length=20, verbose_name='与配公猪号')),
                ('gesage', models.FloatField(default=0, verbose_name='胎龄')),
                ('addpigtime', models.DateField(default='2020-08-16', verbose_name='入栏日期')),
                ('breedtime', models.CharField(max_length=16, verbose_name='配种日期')),
                ('decpigtime', models.DateField(max_length=10, null=True, verbose_name='出栏日期')),
                ('stationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.stationinfo', to_field='build_unit_station', verbose_name='饲喂站号')),
            ],
            options={
                'verbose_name': '动物基础表',
                'db_table': 'tb_pigbase',
            },
        ),
    ]
