# Generated by Django 3.1 on 2020-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pigbase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backfat', models.FloatField(null=True, verbose_name='背膘厚')),
                ('index_quantity', models.FloatField(default=1, verbose_name='默认饲喂量')),
                ('algo_quantity', models.FloatField(null=True, verbose_name='计算饲喂量')),
                ('set_quantity', models.FloatField(null=True, verbose_name='设置饲喂量')),
                ('settime', models.DateField(default='2020-08-16', verbose_name='设置日期')),
                ('pigid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pigbase.pigbase', to_field='pigid', verbose_name='身份码')),
            ],
            options={
                'verbose_name': '饲喂量',
                'verbose_name_plural': '饲喂量',
                'db_table': 'tb_foodquantity',
            },
        ),
        migrations.CreateModel(
            name='Backfat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backfat', models.FloatField(null=True, verbose_name='背膘厚')),
                ('settime', models.DateField(default='2020-08-16', verbose_name='设置日期')),
                ('pigid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pigbase.pigbase', to_field='pigid', verbose_name='身份码')),
            ],
            options={
                'verbose_name': '背膘厚',
                'verbose_name_plural': '背膘厚',
                'db_table': 'tb_backfat',
            },
        ),
    ]
